### ISSUE TITLE
RFC Generic secrets and declarative environment variables

### ISSUE THREAD

**Issue by k2nr** [degica/barcelona#453]
Heavily inspired by [kubernetes secrets](https://kubernetes.io/docs/concepts/configuration/secret/)

# Declarative environment variables

The current environment variables is in a mutable way: run `bcn env set` and it creates or updates the variable. This way has both pros and cons but to make our apps safe and stable, it's better to make it declarative in `barcelona.yml`:

```
prodcution:
  # ...
  environment:
    RAILS_ENV: production
```

Also, making environment declarative will make generic secrets as described below possible.

# Generic Secrets
## Motivation

The current secret environment variable (`bcn env set --secret`) has some downsides.

### It's available only for environment variables

There are other things that we want to make secret such as dockercfg, logentries token (if we add per-app customizable logging driver). It would be great if we can use the same secret mechanism for other things.

### The current way of attaching secret variables can't be declarative

If we add declarative environment variables, we also want to have declarative secret environment variables. But since values of secret environment variables are secret, values should not appear in `barcelona.yml`. We need to have a way so that `barcelona.yml` have a link to a secret value and the  value is stored in somewhere secure (S3 in our case)

## Creating secrets

```
bcn secret create --district=district_name <secret name> <value>
# example
bcn secret create --district=some-district password verysecurepassword
```

## Attaching secrets to environment variables

Instead of specifying string value, use `secret` map

```
production:
  # ...
  environment:
    USER_PASSWORD:
      secret:
        ref: password
```

# Benefits

- environment variable names and values, secret environment variable links can be version-controlled
- In the future we can use generic secrets for other purposes
- Reviewapp #448 can have (secret) environment variables

# Complete Example

```
environments:
  production:
    name: awesome-app
    image_name: awesome-app
    services:
      - name: web
        service_type: web
        cpu: 128
        memory: 256
        command: rails s -p $PORT -b 0.0.0.0
        listeners:
          - endpoint: test-endpoint
        environment:
          RAILS_ENV: production
          SECRET_KEY_BASE:
            secret:
              ref: awesome-app/secret-key-base
          DATABASE_URL:
            secret:
              ref: awesome-app/database-url
```

# Implementation

- Add a new `secrets` table
  - name
  - s3_path
- Add columns to `env_vars` table
  - secret_name
- Secrets are stored in S3 just same as the current secret environment variables

# Compatibility

- the legacy (current) environment variables and declarative environment variables can co-exist.
- Both use the same table (`env_vars`).
- The result set of environment variables that are attached to a container is a union of both legacy and declarative.
- If the same names exist in both legacy and declarative, declarative takes precedent.
- legacy secret environment variable record doesn't have `secret_name` (== `NULL`).
- If `secret_name` is present, `EnvVar` delegates the logic to `secrets`
- If `secret_name` is not present, it falls back to the current way (legacy secret environment variable)

**Comment by k2nr** [comment]
@essa What do you think? just see "Complete Example" to grab the idea

**Comment by essa** [comment]
LGTM, actually I have been hoping Barcelona would have something like this.

The greatest virtue of this plan is having a place for declaration of secret variables required by the app. We can check easily all the variables needed only by looking `barcelona.yml`.

I have one concern.

> If the same names exist in both legacy and declarative, declarative takes precedent.

This may be useful on migration phase but, if Barcelona will keep two ways of setting env vars, I think the reverse is more natural. Command is dynamic so it is natural to have higher priority than declaration which is static.

If you are planning to remove `bcn env set` command in the future, it is ok.

And I have one request.

Could you add a batch mode for `bcn secret` command which can specify source file for multi secret variables?

We have an encrpyted git repository in [Keybase](https://keybase.io/). I'd like to have secrets in  a file  in it.
```
awesome-app/secret-key-base: xxxx
awesome-app/database-url: xxxx
...
```

And load it to a heritage by a command like this.

```
$ bcn secret load -district=some-district shared_secret/awesome-app/secret_envs.yml
```

I think I can track the history of secret variables with an encrypted git repository as well as we can track non-secrets variables with the history of `barcelona.yml`.

**Comment by k2nr** [comment]
batch load is definitely a useful feature! I think that's only a client-side feature so I'll implement basic features for server and client and once it's done we can work on helper commands like batch load

**Comment by k2nr** [comment]
> If you are planning to remove bcn env set command in the future, it is ok.

Yes this is my plan. But I'm still not sure what's the best way to smoothly introduce this new feature while keeping backward compatibility. If you have a better idea, please let me know

**Comment by k2nr** [comment]
## Travis style secrets

Another idea for secrets would be that instead of storing secrets to S3, "create secret" endpoint returns encrypted value with KMS generated data key attached:

```
$ bcn create secret <plaintext secret value>
<encrypted data key>:<encrypted data>
```

Then in `barcelona.yml`

```
environment:
  USER_PASSWORD:
    secret: <encrypted data key>:<encrypted data>
```

The encrypted secret is then decrypted when a container launches (by barcelona-runpack)

## Implementation

- Barcelona service only have `kms:GenerateDataKey` permission
  - When `bcn secret create` is called, Barcelona calls `GenerateDataKey` and get plaintext data key. Then Barcelona encrypts the plaintext data with the generated data key and discard the data key without saving.
  - Each ECS task has a `kms:Decrypt` permission so that containers can decrypt secrets at launching

### Benefits

The benefit of this approach is that secrets can be also version-controlled in `barcelona.yml`

**Comment by k2nr** [comment]
I started thinking the above approach is much better

**Comment by k2nr** [comment]
:thinking: :thinking: 

```
environment:
  USER_PASSWORD_S3:
    secret:
      type: s3
      key: path/to/secret
  USER_PASSWORD_SM:
    secret:
      type: secrets-manager
      key: secrets/manager/key
  USER_PASSWORD_SM:
    secret:
      type: transit
      enc: <encrypted DEK>:<encrypted value>
```
